[metadata]
version = "1.0"

[versions]
indra = "2.1.1"
junit = "5.9.1"

[libraries]
jetbrainsAnnotations = "org.jetbrains:annotations:23.0.0"
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }

[plugins]
indra = { id = "net.kyori.indra", version.ref = "indra" }
indra-publishing-sonatype = { id = "net.kyori.indra.publishing.sonatype", version.ref = "indra" }
spotless = "com.diffplug.spotless:6.6.1"