name: "build"

on:
  push:
    branches: "**"
    tags-ignore: ["**"]
  pull_request:

jobs:
  get-gitconfig:
    runs-on: windows-latest
    steps:
      - uses: KyoriPowered/.github/.github/actions/setup-java-env@trunk
        with:
          runtime_version: 17
          publishing_branch_regex: "trunk"
      - shell: bash
        run: |
          CONF=$(GIT_EDITOR=echo git config --system --edit)
          echo "Config is $CONF"
          cat $CONF
  call-build:
    uses: KyoriPowered/.github/.github/workflows/shared-ci.yaml@trunk
    secrets: inherit
